In [70]:
import pandas as pd
import numpy as np
import os

#### Data Load/Acquisition

In [71]:
temp_df=pd.read_csv('IMDB Dataset.csv')

In [72]:
temp_df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [73]:
temp_df.shape

(50000, 2)

In [74]:
temp_df=temp_df.iloc[:10000]

In [75]:
temp_df.shape

(10000, 2)

In [76]:
temp_df['review'][4]

'Petter Mattei\'s "Love in the Time of Money" is a visually stunning film to watch. Mr. Mattei offers us a vivid portrait about human relations. This is a movie that seems to be telling us what money, power and success do to people in the different situations we encounter. <br /><br />This being a variation on the Arthur Schnitzler\'s play about the same theme, the director transfers the action to the present time New York where all these different characters meet and connect. Each one is connected in one way, or another to the next person, but no one seems to know the previous point of contact. Stylishly, the film has a sophisticated luxurious look. We are taken to see how these people live and the world they live in their own habitat.<br /><br />The only thing one gets out of all these souls in the picture is the different stages of loneliness each one inhabits. A big city is not exactly the best place in which human relations find sincere fulfillment, as one discerns is the case wit

In [77]:
# class distribution
temp_df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [78]:
# checking null values
temp_df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [79]:
# checking duplicate reviews
temp_df.duplicated().sum()

17

In [80]:
#dropping duplicate reviews
temp_df.drop_duplicates(inplace=True)

In [81]:
# checking again duplicate reviews
temp_df.duplicated().sum()

0

#### Text Preprocesssing

In [82]:
# basic text preprocessing
# 1. removing html tags

import re

def remove_tags(text):
    cleaned_text=re.sub(re.compile('<.*?>'),'',text)
    return cleaned_text

In [83]:
temp_df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [84]:
temp_df['review']=temp_df['review'].apply(remove_tags)

In [85]:
temp_df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows wo

In [86]:
# basic text preprocessing
# 2. Converting text into lower case

temp_df['review']=temp_df['review'].apply(lambda x:x.lower())

In [87]:
temp_df['review'][0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wo

In [88]:
# basic text preprocessing
# 3. removing stopwords

import nltk
from nltk.corpus import stopwords

In [89]:
stopword_list=stopwords.words('english')

In [90]:
temp_df['review']=temp_df['review'].apply(lambda x:[i for i in x.split() if i not in stopword_list]).apply(lambda x:" ".join(x))

In [91]:
temp_df['review'][0]

"one reviewers mentioned watching 1 oz episode hooked. right, exactly happened me.the first thing struck oz brutality unflinching scenes violence, set right word go. trust me, show faint hearted timid. show pulls punches regards drugs, sex violence. hardcore, classic use word.it called oz nickname given oswald maximum security state penitentary. focuses mainly emerald city, experimental section prison cells glass fronts face inwards, privacy high agenda. em city home many..aryans, muslims, gangstas, latinos, christians, italians, irish more....so scuffles, death stares, dodgy dealings shady agreements never far away.i would say main appeal show due fact goes shows dare. forget pretty pictures painted mainstream audiences, forget charm, forget romance...oz mess around. first episode ever saw struck nasty surreal, say ready it, watched more, developed taste oz, got accustomed high levels graphic violence. violence, injustice (crooked guards who'll sold nickel, inmates who'll kill order g

In [92]:
# basic text preprocessing
# 4. removing punctuations

import string

In [93]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [94]:
exclude=string.punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans('','',exclude))

In [95]:
temp_df['review']=temp_df['review'].apply(remove_punctuation)

In [96]:
temp_df['review'][0]

'one reviewers mentioned watching 1 oz episode hooked right exactly happened methe first thing struck oz brutality unflinching scenes violence set right word go trust me show faint hearted timid show pulls punches regards drugs sex violence hardcore classic use wordit called oz nickname given oswald maximum security state penitentary focuses mainly emerald city experimental section prison cells glass fronts face inwards privacy high agenda em city home manyaryans muslims gangstas latinos christians italians irish moreso scuffles death stares dodgy dealings shady agreements never far awayi would say main appeal show due fact goes shows dare forget pretty pictures painted mainstream audiences forget charm forget romanceoz mess around first episode ever saw struck nasty surreal say ready it watched more developed taste oz got accustomed high levels graphic violence violence injustice crooked guards wholl sold nickel inmates wholl kill order get away it well mannered middle class inmates t

In [97]:
# basic text preprocessing
# 5. Stemming

from nltk.stem.porter import PorterStemmer

ps=PorterStemmer()

def stem_words(text):
    return " ".join ([ps.stem(i) for i in text.split()])

In [98]:
temp_df['review']=temp_df['review'].apply(stem_words)

In [99]:
temp_df['review'][0]

'one review mention watch 1 oz episod hook right exactli happen meth first thing struck oz brutal unflinch scene violenc set right word go trust me show faint heart timid show pull punch regard drug sex violenc hardcor classic use wordit call oz nicknam given oswald maximum secur state penitentari focus mainli emerald citi experiment section prison cell glass front face inward privaci high agenda em citi home manyaryan muslim gangsta latino christian italian irish moreso scuffl death stare dodgi deal shadi agreement never far awayi would say main appeal show due fact goe show dare forget pretti pictur paint mainstream audienc forget charm forget romanceoz mess around first episod ever saw struck nasti surreal say readi it watch more develop tast oz got accustom high level graphic violenc violenc injustic crook guard wholl sold nickel inmat wholl kill order get away it well manner middl class inmat turn prison bitch due lack street skill prison experi watch oz may becom comfort uncomfor

In [100]:
temp_X=temp_df.iloc[:,0:1]
temp_y=temp_df['sentiment']

In [101]:
temp_X.head()

review
0  one review mention watch 1 oz episod hook righ...
1  wonder littl product film techniqu unassum old...
2  thought wonder way spend time hot summer weeke...
3  basic there famili littl boy jake think there ...
4  petter mattei love time money visual stun film...

In [102]:
temp_y.head()

0    positive
1    positive
2    positive
3    negative
4    positive
Name: sentiment, dtype: object

In [103]:
#since temp_y is in english. Converting it into number for the ease of modeling

from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()

temp_y=encoder.fit_transform(temp_y)

In [104]:
temp_y

array([1, 1, 1, ..., 0, 0, 1])

In [105]:
#Spliting the data into train and test

from sklearn.model_selection import train_test_split
Xtrain, Xtest,ytrain, ytest=train_test_split(temp_X,temp_y, test_size=0.2, random_state=1)


In [106]:
Xtrain.shape

(7986, 1)

In [107]:
Xtest.shape

(1997, 1)

In [108]:
ytrain

array([1, 1, 0, ..., 0, 0, 1])

In [109]:
Xtrain

review
6713  ive wait superhero movi like long time mysteri...
1178  movi excel act excel direct overal excel stori...
4707  movi make want throw everi time see it take fi...
6772  first saw movi elementari school back 1960 fas...
7461  show made person iq lower 80 joke show lame de...
...                                                 ...
2895  excel episod movi ala pulp fiction 7 day 7 sui...
7823  first off give idea tast movies2007 comedi enj...
905   well begin stori went movi tonight friend know...
5195  lot horror fan seem love scarecrow popular say...
235   rees witherspoon first outing big screen memor...

[7986 rows x 1 columns]

#### Text Vectorization

##### Bag of Words

In [121]:
from sklearn.feature_extraction.text import CountVectorizer

In [122]:
cv=CountVectorizer()

In [123]:
X_train_bow = cv.fit_transform(Xtrain['review']).toarray()
X_test_bow = cv.transform(Xtest['review']).toarray()


#cv_train  = cv.fit_transform(X_train)
#cv_test = cv.transform(X_test)

In [124]:
X_train_bow.shape

(7986, 55213)

In [125]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [126]:
X_test_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

#### Data Modelling

##### Naive Bayes

In [127]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()


gnb.fit(X_train_bow,ytrain)

GaussianNB()

In [128]:
y_pred = gnb.predict(X_test_bow)

In [129]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [130]:
accuracy_score(ytest,y_pred)

0.6464697045568353

In [131]:
confusion_matrix(ytest,y_pred)

array([[681, 271],
       [435, 610]], dtype=int64)

##### Random Forest on BOW

In [132]:
from sklearn.ensemble import RandomForestClassifier

rf= RandomForestClassifier()

In [133]:
rf.fit(X_train_bow,ytrain)

RandomForestClassifier()

In [134]:
y_pred_rf=rf.predict(X_test_bow)

In [136]:
accuracy_score(ytest,y_pred_rf)

0.8407611417125689

In [137]:
confusion_matrix(ytest,y_pred_rf)

array([[799, 153],
       [165, 880]], dtype=int64)

In [138]:
# To improve the accuracy trying to use vocabulary's most frequent words rather than entire vocab
# so we have 55213 words. 
# trying to use most frequent 3k words
X_train_bow.shape

(7986, 55213)

In [139]:
cv_new=CountVectorizer(max_features=3000)

X_train_bow_new = cv_new.fit_transform(Xtrain['review']).toarray()
X_test_bow_new = cv_new.transform(Xtest['review']).toarray()

rf_new=RandomForestClassifier()

rf_new.fit(X_train_bow_new,ytrain)

y_pred_rf_new=rf_new.predict(X_test_bow_new)

In [140]:
accuracy_score(ytest,y_pred_rf_new)

0.8357536304456685

In [141]:
confusion_matrix(ytest,y_pred_rf_new)

array([[795, 157],
       [171, 874]], dtype=int64)

##### Random Forest on nGrams

In [142]:
#Since without max feature the model was throwing 'memory error' as vocab for bi gram and tri gram has increased exponentially

cv_ng=CountVectorizer(ngram_range=(1,2),max_features=10000)

X_train_bow_ng = cv_ng.fit_transform(Xtrain['review']).toarray()
X_test_bow_ng = cv_ng.transform(Xtest['review']).toarray()

rf_ng=RandomForestClassifier()

rf_ng.fit(X_train_bow_ng,ytrain)

y_pred_rf_ng=rf_ng.predict(X_test_bow_ng)

In [143]:
accuracy_score(ytest,y_pred_rf_ng)

0.8432648973460191

In [144]:
cv_ng=CountVectorizer(ngram_range=(1,3),max_features=10000)

X_train_bow_ng = cv_ng.fit_transform(Xtrain['review']).toarray()
X_test_bow_ng = cv_ng.transform(Xtest['review']).toarray()

rf_ng=RandomForestClassifier()

rf_ng.fit(X_train_bow_ng,ytrain)

y_pred_rf_ng=rf_ng.predict(X_test_bow_ng)

In [146]:
accuracy_score(ytest,y_pred_rf_ng)

0.8382573860791187

##### Random Forest on Tfidf 

In [147]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [148]:
tfidf=TfidfVectorizer()

In [149]:
X_train_tfidf = tfidf.fit_transform(Xtrain['review']).toarray()
X_test_tfidf = tfidf.transform(Xtest['review']).toarray()

In [150]:
rf_tfidf=RandomForestClassifier()

rf_tfidf.fit(X_train_tfidf,ytrain)

y_pred_tfidf=rf_tfidf.predict(X_test_tfidf)

In [151]:
accuracy_score(ytest,y_pred_tfidf)

0.8422633950926389

##### Word2Vec

In [152]:
import gensim

In [153]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [154]:
story=[]

for doc in temp_df['review']:
    raw_sent=sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [157]:
story

[['one',
  'review',
  'mention',
  'watch',
  'oz',
  'episod',
  'hook',
  'right',
  'exactli',
  'happen',
  'meth',
  'first',
  'thing',
  'struck',
  'oz',
  'brutal',
  'unflinch',
  'scene',
  'violenc',
  'set',
  'right',
  'word',
  'go',
  'trust',
  'me',
  'show',
  'faint',
  'heart',
  'timid',
  'show',
  'pull',
  'punch',
  'regard',
  'drug',
  'sex',
  'violenc',
  'hardcor',
  'classic',
  'use',
  'wordit',
  'call',
  'oz',
  'nicknam',
  'given',
  'oswald',
  'maximum',
  'secur',
  'state',
  'penitentari',
  'focus',
  'mainli',
  'emerald',
  'citi',
  'experiment',
  'section',
  'prison',
  'cell',
  'glass',
  'front',
  'face',
  'inward',
  'privaci',
  'high',
  'agenda',
  'em',
  'citi',
  'home',
  'manyaryan',
  'muslim',
  'gangsta',
  'latino',
  'christian',
  'italian',
  'irish',
  'moreso',
  'scuffl',
  'death',
  'stare',
  'dodgi',
  'deal',
  'shadi',
  'agreement',
  'never',
  'far',
  'awayi',
  'would',
  'say',
  'main',
  'appeal'

In [155]:
model = gensim.models.Word2Vec (window=10, min_count=2)


In [156]:
model

In [158]:
model.build_vocab(story)

In [159]:
model.train(story, total_examples=model.corpus_count,epochs=model.epochs)

(5535550, 6021045)

In [161]:
len(model.wv.index_to_key)

24859

In [ ]:
# till this point we have build the model (word2vec) for words. Now..going to create the same for documents i.e. reviews

In [166]:
def document_vector(doc):
    # remove out of vocab words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc],axis=0)

In [167]:
document_vector(temp_df['review'].values[0])

array([-0.16148888,  0.21170482,  0.13300516,  0.02996575, -0.05955967,
       -0.6566363 ,  0.24752004,  0.8238588 , -0.20811972, -0.25771484,
        0.08338922, -0.3236677 ,  0.14897458,  0.11516476, -0.03304948,
       -0.13469313,  0.2236891 , -0.48195055,  0.02106981, -0.76464856,
        0.10818195,  0.09295291,  0.08617388, -0.19250533, -0.16087016,
        0.07089908, -0.30069482, -0.27718323, -0.3112969 , -0.02038735,
        0.3901    ,  0.16038491,  0.32488787, -0.28502545, -0.09162693,
        0.33055475,  0.10039371, -0.43100795, -0.4852885 , -0.52665067,
       -0.03299392, -0.2594604 , -0.1836513 , -0.09272141,  0.27161735,
       -0.39819887, -0.25427318, -0.20106559,  0.28994048,  0.36194527,
        0.03528636, -0.04307402, -0.14068873,  0.28989273, -0.18782863,
        0.03606995,  0.31028494, -0.21448119, -0.2552766 ,  0.17735669,
        0.09339427,  0.1980925 , -0.05887982,  0.08612438, -0.3566081 ,
        0.3171464 , -0.03496544,  0.20611088, -0.45602006,  0.22

In [168]:
from tqdm import tqdm

In [169]:
W2V =[]

for doc in tqdm(temp_df['review'].values):
    W2V.append(document_vector(doc))


100%|██████████| 9983/9983 [01:57<00:00, 85.11it/s] 


In [170]:
W=np.array(W2V)

In [171]:
W[1]

array([-0.14950939,  0.20378998,  0.12206046,  0.16207257,  0.2000514 ,
       -0.75567096,  0.21779208,  0.7460144 , -0.4670066 , -0.3242641 ,
       -0.39441603, -0.65607715, -0.01972413,  0.28322992,  0.23533817,
       -0.03038423, -0.02566522, -0.47483972,  0.0260251 , -0.67291665,
        0.08465349,  0.59185594,  0.51707155, -0.29735824,  0.24178861,
        0.38096645, -0.34588218, -0.0966941 , -0.2926375 ,  0.20159054,
        0.51017445, -0.3001806 ,  0.23422848, -0.61515725, -0.2633919 ,
        0.74080336,  0.15521267, -0.45840272, -0.37300423, -0.5123727 ,
        0.09035689, -0.32773417, -0.10427334,  0.01408936, -0.01568785,
       -0.18495362, -0.4853369 , -0.22022615,  0.05631595,  0.01804903,
        0.2224913 , -0.70003307, -0.1651967 ,  0.142759  , -0.08170895,
        0.33797878,  0.15601394, -0.2614192 , -0.06805492,  0.08840077,
        0.11937974, -0.12106767,  0.20090592,  0.08933648, -0.45075104,
        0.2678723 ,  0.38724613,  0.25066257, -0.75743896,  0.40

In [172]:
W.shape

(9983, 100)

In [173]:
from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()

V=encoder.fit_transform(temp_y)

In [174]:
V

array([1, 1, 1, ..., 0, 0, 1], dtype=int64)

In [175]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest,ytrain, ytest=train_test_split(W,V, test_size=0.2, random_state=1)

In [176]:
rf_w2v=RandomForestClassifier()

In [178]:
rf_w2v.fit(Xtrain,ytrain)

y_pred_w2vf=rf_w2v.predict(Xtest)

In [180]:
accuracy_score(ytest, y_pred_w2vf)

0.8182273410115173

In [187]:
y_pred_w2vf[[0,1,13,26,32,56]]

array([1, 1, 1, 1, 1, 0], dtype=int64)

In [188]:
temp_df['review'][0]

'one review mention watch 1 oz episod hook right exactli happen meth first thing struck oz brutal unflinch scene violenc set right word go trust me show faint heart timid show pull punch regard drug sex violenc hardcor classic use wordit call oz nicknam given oswald maximum secur state penitentari focus mainli emerald citi experiment section prison cell glass front face inward privaci high agenda em citi home manyaryan muslim gangsta latino christian italian irish moreso scuffl death stare dodgi deal shadi agreement never far awayi would say main appeal show due fact goe show dare forget pretti pictur paint mainstream audienc forget charm forget romanceoz mess around first episod ever saw struck nasti surreal say readi it watch more develop tast oz got accustom high level graphic violenc violenc injustic crook guard wholl sold nickel inmat wholl kill order get away it well manner middl class inmat turn prison bitch due lack street skill prison experi watch oz may becom comfort uncomfor

In [189]:
temp_df['review'][56]

'hill eye ii would expect noth more cours go oscar nomin film pure entertain lose 90 minutesth plot basic group nation guard traine find battl notori mutat hillbilli last day train desert fight back throughout whole film includ lot violenc which basic whole film blood gut constantli fli around throughout whole thing also yet anoth graphic rape scene pointlessli thrown shock audienceid give hill eye ii 4 10 pure entertain onli although even found look watch film went on began drag due fact continu tri shock audienc graphic gore occasion jump scene make sure audienc stay awak hill eye ii decent entertain someth pass time bore noth else410'